import { Platform, StyleSheet } from "react-native";

import { colors } from "../theme/colors";

export const chatInboxStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  screen: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    backgroundColor: colors.surface,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.slateSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  headerText: { flex: 1, marginLeft: 12 },
  title: { color: colors.text, fontSize: 18, fontWeight: "800", letterSpacing: -0.2 },
  subtitle: { color: colors.mutedText, fontSize: 11, lineHeight: 15, fontWeight: "600", marginTop: 2 },
  content: { flex: 1 },
  list: { flexGrow: 1, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 22 },
  loadingState: { alignItems: "center", paddingTop: 56, gap: 12 },
  loadingText: { color: colors.mutedText, fontSize: 13, fontWeight: "600" },
  errorState: { alignItems: "center", paddingHorizontal: 24, paddingTop: 52 },
  errorIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: colors.crimsonBorder,
    backgroundColor: colors.crimsonSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  errorTitle: { color: colors.text, fontSize: 16, fontWeight: "800", marginTop: 12 },
  errorText: { color: colors.mutedText, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 6 },
  retryButton: {
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: colors.crimson,
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 12,
  },
  retryText: { color: colors.surface, fontSize: 13, fontWeight: "700" },
  pressed: { opacity: 0.85 },
  emptyState: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 30, paddingTop: 52 },
  emptyIcon: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: { color: colors.text, fontSize: 16, fontWeight: "700", marginTop: 12 },
  emptyText: { color: colors.mutedText, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 6 },
  threadRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 12,
  },
  avatarWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.crimsonSoft,
    borderWidth: 1,
    borderColor: colors.crimsonBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: colors.crimson, fontSize: 12, fontWeight: "800" },
  threadBody: { flex: 1 },
  threadHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 },
  threadName: { color: colors.text, fontSize: 15, fontWeight: "700", flexShrink: 1 },
  threadTime: { color: colors.mutedText, fontSize: 11, fontWeight: "600" },
  threadRole: { color: colors.mutedText, fontSize: 11, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.9, marginTop: 3 },
  metaRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 8, flexShrink: 1 },
  bloodPill: {
    backgroundColor: colors.crimsonSoft,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    color: colors.crimson,
    fontSize: 11,
    fontWeight: "800",
  },
  metaText: { color: colors.mutedText, fontSize: 11, fontWeight: "600", flexShrink: 1 },
  preview: { color: colors.text, fontSize: 12, lineHeight: 18, marginTop: 8 },
});
