import { Platform, StyleSheet } from "react-native";

import { colors } from "../theme/colors";

export const chatStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  keyboardView: { flex: 1 },
  screen: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    backgroundColor: colors.surface,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.slateSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  headerText: { flex: 1, marginLeft: 12 },
  title: { color: colors.text, fontSize: 18, fontWeight: "800", letterSpacing: -0.2 },
  subtitle: { color: colors.mutedText, fontSize: 11, lineHeight: 15, fontWeight: "600", marginTop: 2 },
  headerAction: { width: 36, alignItems: "center", justifyContent: "center" },
  reconnectBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 8,
    backgroundColor: "#fff7ed",
    borderBottomWidth: 1,
    borderBottomColor: "#fed7aa",
  },
  reconnectText: { color: colors.amberText, fontSize: 12, fontWeight: "700" },
  contextStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 10,
    backgroundColor: colors.background,
  },
  contextPill: {
    minHeight: 36,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    justifyContent: "center",
  },
  contextPillWide: {
    minHeight: 36,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    justifyContent: "center",
    flexBasis: "100%",
  },
  contextLabel: { color: colors.mutedText, fontSize: 10, fontWeight: "700", letterSpacing: 0.9, textTransform: "uppercase" },
  contextValue: { color: colors.text, fontSize: 12, fontWeight: "700", marginTop: 2 },
  contextValueCritical: { color: colors.crimson },
  contextValueUrgent: { color: colors.amberText },
  content: { flex: 1 },
  list: { flexGrow: 1, paddingHorizontal: 16, paddingTop: 8, paddingBottom: 18 },
  messageRow: { flexDirection: "row", alignItems: "flex-end", marginBottom: 12 },
  sentRow: { justifyContent: "flex-end" },
  receivedRow: { justifyContent: "flex-start" },
  avatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.crimsonSoft,
    borderWidth: 1,
    borderColor: colors.crimsonBorder,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  avatarText: { color: colors.crimson, fontSize: 10, fontWeight: "800" },
  bubble: {
    maxWidth: "76%",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    shadowColor: colors.text,
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 2,
    elevation: 1,
  },
  sentBubble: { backgroundColor: colors.crimson, borderBottomRightRadius: 6 },
  receivedBubble: { backgroundColor: colors.surface, borderWidth: 1, borderColor: "#e2e8f0", borderBottomLeftRadius: 6 },
  messageText: { color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: "500" },
  sentText: { color: colors.surface },
  time: { marginTop: 6, fontSize: 10, fontWeight: "600", color: colors.mutedText },
  sentTime: { color: "rgba(255,255,255,0.78)" },
  emptyState: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 32 },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  emptyTitle: { color: colors.text, fontSize: 16, fontWeight: "700" },
  emptyText: { color: colors.mutedText, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 4 },
  inputContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: Platform.OS === "ios" ? 20 : 12,
  },
  inputShell: {
    flex: 1,
    minHeight: 46,
    maxHeight: 120,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  input: { color: colors.text, fontSize: 14, lineHeight: 20, paddingVertical: 0 },
  sendButton: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: colors.crimson,
    alignItems: "center",
    justifyContent: "center",
  },
  sendButtonDisabled: { backgroundColor: "#e2e8f0" },

  // --- Loading / error full-screen states, matching RequestDetailScreen ---
  loadingState: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 },
  loadingText: { color: colors.mutedText, fontSize: 13, fontWeight: "600" },
  errorState: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 24 },
  errorIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: colors.crimsonBorder,
    backgroundColor: colors.crimsonSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  errorTitle: { color: colors.text, fontSize: 16, fontWeight: "800", marginTop: 12, textAlign: "center" },
  errorText: { color: colors.mutedText, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 6 },
  errorActions: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 18 },
  retryButton: { paddingHorizontal: 18, paddingVertical: 11, borderRadius: 12, backgroundColor: colors.crimson, flexDirection: "row", alignItems: "center", gap: 6 },
  retryText: { color: colors.surface, fontSize: 13, fontWeight: "800" },
  pressed: { opacity: 0.85 },

  // --- Send-failure banner, above the input ---
  sendErrorBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 6,
    backgroundColor: colors.crimsonSoft,
  },
  sendErrorText: { color: colors.crimson, fontSize: 11, fontWeight: "700", flex: 1 },

  // --- Pending / failed outgoing bubbles ---
  bubblePending: { opacity: 0.6 },
  bubbleFailed: { borderWidth: 1, borderColor: colors.crimson },
  retryHint: { marginTop: 4, fontSize: 10, fontWeight: "700", color: colors.crimson },
});
