import { StyleSheet } from "react-native";

import { colors } from "../theme/colors";

export const createEmergencyRequestStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  screen: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 10,
    minHeight: 54,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  backButton: {
    position: "absolute",
    left: 0,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  titleWrap: { flexDirection: "row", alignItems: "center", gap: 10, paddingLeft: 0 },
  titleDotWrap: {
    width: 12,
    height: 12,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  titleDot: {
    position: "absolute",
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.crimson,
  },
  titleDotCore: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.crimson,
    position: "absolute",
    zIndex: 1,
  },
  title: { color: colors.text, fontSize: 18, lineHeight: 22, fontWeight: "700", letterSpacing: -0.2 },
  content: { paddingHorizontal: 18, paddingTop: 12, paddingBottom: 32 },
  form: { gap: 18 },
  infoBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    borderRadius: 16,
    backgroundColor: "#fff8f8",
    borderWidth: 1,
    borderColor: "#f7d9d9",
    padding: 14,
  },
  infoIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#fff1f2",
    alignItems: "center",
    justifyContent: "center",
  },
  infoText: { flex: 1, color: "#475569", fontSize: 13.5, lineHeight: 20 },
  fieldCard: {
    backgroundColor: "#f8fafc",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 14,
  },
  label: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: "700", marginBottom: 10 },
  sectionHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  sectionHint: { color: "#64748b", fontSize: 12, lineHeight: 16, fontWeight: "600" },
  inputShell: {
    height: 52,
    borderRadius: 12,
    backgroundColor: "#f1f5f9",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  inputShellRow: {
    height: 52,
    borderRadius: 12,
    backgroundColor: "#f1f5f9",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
  },
  phoneFields: { flexDirection: "row", alignItems: "center", gap: 8 },
  countryCode: {
    width: 92,
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.crimsonBorder,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    color: colors.text,
    fontSize: 15,
  },
  numberInput: {
    flex: 1,
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.crimsonBorder,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    color: colors.text,
    fontSize: 15,
  },
  inputFocused: {
    borderColor: colors.crimson,
    shadowColor: colors.crimson,
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
  },
  input: { flex: 1, color: colors.text, fontSize: 15, paddingVertical: 0, fontWeight: "500" },
  inputShellError: { borderColor: colors.crimson, backgroundColor: colors.crimsonSoft },
  fieldError: { marginTop: 8, color: colors.crimson, fontSize: 12, lineHeight: 16, fontWeight: "600" },
  generalError: { marginBottom: 12, color: colors.crimson, fontSize: 13, lineHeight: 18, fontWeight: "600" },
  deadlineGrid: { flexDirection: "row", gap: 8, marginBottom: 10 },
  requiredByControls: { flexDirection: "row", gap: 8 },
  requiredByButton: { flex: 1, minWidth: 0, minHeight: 58, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 12, borderWidth: 1, borderColor: "#e2e8f0", backgroundColor: "#f1f5f9", flexDirection: "row", alignItems: "center", gap: 8 },
  requiredByButtonCopy: { flex: 1, minWidth: 0 },
  requiredByButtonLabel: { color: colors.subtleText, fontSize: 9, fontWeight: "800", letterSpacing: 0.8 },
  requiredByButtonValue: { color: colors.text, fontSize: 12, lineHeight: 16, fontWeight: "800", marginTop: 2 },
  requiredByPreview: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 9 },
  requiredByPreviewText: { color: colors.mutedText, fontSize: 11, fontWeight: "600" },
  pickerBackdrop: { flex: 1, backgroundColor: "rgba(15,23,42,0.48)", justifyContent: "flex-end" },
  pickerDismissArea: { flex: 1 },
  pickerSheet: { backgroundColor: colors.surface, borderTopLeftRadius: 26, borderTopRightRadius: 26, paddingHorizontal: 20, paddingTop: 10, paddingBottom: 26 },
  pickerHandle: { width: 46, height: 5, borderRadius: 3, backgroundColor: "#cbd5e1", alignSelf: "center", marginBottom: 12 },
  pickerTitleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 18 },
  pickerTitle: { color: colors.text, fontSize: 20, fontWeight: "800" },
  timeHint: { color: colors.mutedText, fontSize: 12, marginBottom: 16 },
  timePickerRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  timeStepper: { alignItems: "center", gap: 5 },
  stepperButton: { width: 38, height: 34, borderRadius: 9, backgroundColor: colors.slateSoft, alignItems: "center", justifyContent: "center" },
  timeValue: { minWidth: 48, textAlign: "center", color: colors.text, fontSize: 30, fontWeight: "800" },
  timeSeparator: { color: colors.text, fontSize: 28, fontWeight: "800", marginBottom: 2 },
  meridiemColumn: { gap: 5, marginLeft: 4 },
  meridiemButton: { width: 48, height: 30, borderRadius: 8, alignItems: "center", justifyContent: "center", backgroundColor: colors.slateSoft },
  meridiemSelected: { backgroundColor: colors.crimson },
  meridiemText: { color: colors.text, fontSize: 11, fontWeight: "800" },
  pickerDoneButton: { height: 48, borderRadius: 12, backgroundColor: colors.crimson, alignItems: "center", justifyContent: "center", marginTop: 22 },
  pickerDoneText: { color: colors.surface, fontSize: 14, fontWeight: "800" },
  calendarHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 8 },
  calendarNavButton: { width: 30, height: 30, borderRadius: 8, backgroundColor: "#f1f5f9", alignItems: "center", justifyContent: "center" },
  calendarMonth: { color: colors.text, fontSize: 13, fontWeight: "800" },
  calendarWeekRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  calendarWeekDay: { width: "14.28%", color: colors.subtleText, fontSize: 10, fontWeight: "800", textAlign: "center" },
  calendarGrid: { flexDirection: "row", flexWrap: "wrap", rowGap: 4 },
  calendarDay: { width: "14.28%", height: 32, alignItems: "center", justifyContent: "center" },
  calendarDaySelected: { borderRadius: 16, backgroundColor: colors.crimson },
  calendarDayDisabled: { opacity: 0.35 },
  calendarDayText: { color: colors.text, fontSize: 12, fontWeight: "700" },
  calendarDayTextSelected: { color: colors.surface },
  calendarDayTextDisabled: { color: colors.subtleText },
  calendarHint: { color: colors.mutedText, fontSize: 11, lineHeight: 16, marginTop: 8, marginBottom: 9 },
  deadlineOption: {
    flex: 1,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#f1f5f9",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    alignItems: "center",
    justifyContent: "center",
  },
  deadlineOptionSelected: { backgroundColor: colors.crimson, borderColor: colors.crimson },
  deadlineText: { color: "#334155", fontSize: 12, fontWeight: "700" },
  deadlineTextSelected: { color: colors.surface },
  retryLocation: { marginTop: 10, flexDirection: "row", alignItems: "center", gap: 6, alignSelf: "flex-start" },
  retryLocationText: { color: colors.crimson, fontSize: 14, fontWeight: "600" },
  bloodGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", rowGap: 8 },
  bloodOption: {
    width: "23.5%",
    height: 44,
    borderRadius: 10,
    backgroundColor: "#f1f5f9",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    alignItems: "center",
    justifyContent: "center",
  },
  bloodOptionSelected: { backgroundColor: colors.crimson, borderColor: colors.crimson, shadowColor: colors.crimson, shadowOpacity: 0.18, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  bloodOptionText: { color: colors.text, fontSize: 15, fontWeight: "700" },
  bloodOptionTextSelected: { color: colors.surface },
  stepperWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 12,
    backgroundColor: "#f1f5f9",
    padding: 8,
    gap: 8,
  },
  stepButton: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  stepButtonPrimary: { backgroundColor: colors.crimson, borderColor: colors.crimson },
  unitText: { flex: 1, textAlign: "center", color: colors.crimson, fontSize: 17, fontWeight: "800" },
  priorityLabel: { color: colors.crimson, fontSize: 11, lineHeight: 14, fontWeight: "700", letterSpacing: 0.4, textTransform: "uppercase" },
  urgencyGrid: { flexDirection: "row", gap: 8 },
  urgencyOption: {
    flex: 1,
    backgroundColor: "#f8fafc",
    borderWidth: 2,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    minHeight: 76,
    justifyContent: "space-between",
  },
  urgencyHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  urgencyDot: { width: 10, height: 10, borderRadius: 5 },
  urgencyCheck: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: "#cbd5e1",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  urgencyText: { color: "#334155", fontSize: 14, fontWeight: "700", marginTop: 8 },
  helpText: { marginTop: 10, color: "#64748b", fontSize: 12.5, lineHeight: 18 },
  subLabel: { color: "#64748b", fontSize: 12.5, lineHeight: 16, marginBottom: 10 },
  locationBlock: {
    borderRadius: 14,
    backgroundColor: "#dcfce7",
    borderWidth: 1,
    borderColor: "#bbf7d0",
    padding: 12,
  },
  locationRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  locationLeft: { flexDirection: "row", alignItems: "center", gap: 10, flex: 1, marginRight: 8 },
  locationIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#bbf7d0",
    alignItems: "center",
    justifyContent: "center",
  },
  locationTextWrap: { flex: 1, minWidth: 0 },
  locationTitle: { color: colors.text, fontSize: 14, lineHeight: 18, fontWeight: "700", flexShrink: 1 },
  locationMeta: { color: "#0f766e", fontSize: 11.5, lineHeight: 16, marginTop: 2, fontWeight: "600", flexShrink: 1 },
  locationCheckWrap: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#22c55e",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 6,
  },
  locationCheckWrapPending: { backgroundColor: "#94a3b8" },
  subtleText: { color: "#64748b", fontSize: 12, lineHeight: 18, marginTop: 10 },
  dateLeft: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1 },
  dateText: { color: colors.text, fontSize: 14, fontWeight: "700" },
  ctaWrap: { marginTop: 4 },
  cta: {
    width: "100%",
    height: 56,
    borderRadius: 16,
    backgroundColor: colors.crimson,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.crimson,
    shadowOpacity: 0.26,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 4,
  },
  ctaPressed: { opacity: 0.92 },
  ctaDisabled: { opacity: 0.55 },
  ctaIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  ctaText: { color: colors.surface, fontSize: 15, lineHeight: 20, fontWeight: "800" },
  trustRow: { marginTop: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  trustText: { color: "#475569", fontSize: 12.5, lineHeight: 18 },
});
