import { StyleSheet } from "react-native";

import { colors } from "../theme/colors";

export const donorProfileStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  screen: { flex: 1, backgroundColor: colors.background },
  scrollContent: { paddingBottom: 88 },
  profileHeader: { alignItems: "center", paddingHorizontal: 16, paddingTop: 18, paddingBottom: 22 },
  avatarWrap: { position: "relative", marginBottom: 9 },
  avatar: { width: 96, height: 96, borderRadius: 48, backgroundColor: colors.primaryFixed ?? "#ffdad8", alignItems: "center", justifyContent: "center", shadowColor: colors.text, shadowOpacity: 0.1, shadowRadius: 6, shadowOffset: { width: 0, height: 3 }, elevation: 3 },
  avatarText: { color: colors.crimson, fontSize: 30, fontWeight: "800" },
  // Inset to the parent's content box by absolute positioning rather than a
  // fixed size, so the same rule works under the requestor avatar's 4px ring.
  // borderRadius above half the box just clamps, which is what makes it a circle.
  avatarImage: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, borderRadius: 48 },
  avatarBusy: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, borderRadius: 48, backgroundColor: "rgba(15,23,42,0.45)", alignItems: "center", justifyContent: "center" },
  photoError: { color: colors.crimson, fontSize: 11, lineHeight: 16, fontWeight: "600", textAlign: "center", marginTop: 8, paddingHorizontal: 12 },
  cameraButton: { position: "absolute", right: 0, bottom: 0, width: 32, height: 32, borderRadius: 16, backgroundColor: colors.crimson, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: colors.background },
  nameRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 8 },
  name: { color: colors.text, fontSize: 22, fontWeight: "700" },
  nameEditButton: { padding: 4 },
  badges: { flexDirection: "row", flexWrap: "wrap", justifyContent: "center", gap: 8, marginBottom: 7 },
  bloodBadge: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 999, backgroundColor: colors.crimsonSoft, flexDirection: "row", alignItems: "center", gap: 5 },
  bloodText: { color: colors.crimson, fontSize: 11, fontWeight: "700" },
  verifiedBadge: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 999, backgroundColor: "#6cf8bb", flexDirection: "row", alignItems: "center", gap: 5 },
  verifiedText: { color: colors.emeraldText, fontSize: 11, fontWeight: "700" },
  unverifiedBadge: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 999, backgroundColor: colors.amberSoft, borderWidth: 1, borderColor: colors.amberBorder, flexDirection: "row", alignItems: "center", gap: 5 },
  unverifiedText: { color: colors.amberText, fontSize: 11, fontWeight: "700" },
  memberSince: { color: colors.mutedText, fontSize: 11 },
  content: { paddingHorizontal: 16, gap: 18 },
  availabilityCard: { padding: 14, borderRadius: 12, backgroundColor: colors.surface, shadowColor: colors.text, shadowOpacity: 0.08, shadowRadius: 5, shadowOffset: { width: 0, height: 2 }, elevation: 2, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  availabilityCopy: { flex: 1, flexDirection: "row", alignItems: "flex-start", gap: 10 },
  availabilityIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: "#6cf8bb", alignItems: "center", justifyContent: "center" },
  availabilityPulse: { position: "absolute", width: 10, height: 10, top: -1, right: -1, borderRadius: 5, backgroundColor: colors.secondary },
  availabilityCore: { position: "absolute", width: 10, height: 10, top: -1, right: -1, borderRadius: 5, backgroundColor: colors.secondary },
  availabilityPulseOff: { backgroundColor: "#94a3b8" },
  availabilityCoreOff: { backgroundColor: "#94a3b8" },
  availabilityBusy: { opacity: 0.7 },
  availabilityError: { color: colors.crimson, fontSize: 11, lineHeight: 16, fontWeight: "600", marginTop: 8, paddingHorizontal: 4 },
  availabilityText: { color: colors.text, fontSize: 14, fontWeight: "600" },
  availabilitySubtext: { color: colors.mutedText, fontSize: 10, lineHeight: 14, marginTop: 2 },
  switch: { width: 48, height: 28, borderRadius: 14, backgroundColor: colors.secondary, padding: 3, justifyContent: "center" },
  switchOff: { backgroundColor: "#dae2fd" },
  switchThumb: { width: 22, height: 22, borderRadius: 11, backgroundColor: colors.surface, shadowColor: colors.text, shadowOpacity: 0.15, shadowRadius: 3, shadowOffset: { width: 0, height: 1 }, elevation: 2 },
  switchThumbOn: { alignSelf: "flex-end" },
  section: { gap: 6 },
  sectionLabel: { color: colors.mutedText, fontSize: 10, fontWeight: "700", letterSpacing: 1.1, textTransform: "uppercase", paddingHorizontal: 4 },
  sectionCard: { borderRadius: 12, backgroundColor: colors.surface, overflow: "hidden", shadowColor: colors.text, shadowOpacity: 0.06, shadowRadius: 4, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  row: { minHeight: 64, paddingHorizontal: 14, paddingVertical: 11, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  rowIcon: { width: 40, height: 40, borderRadius: 8, backgroundColor: "#eaedff", alignItems: "center", justifyContent: "center" },
  rowCopy: { flex: 1, minWidth: 0, marginLeft: 10 },
  rowLabel: { color: colors.mutedText, fontSize: 10 },
  rowValue: { color: colors.text, fontSize: 12, fontWeight: "600", marginTop: 2 },
  rowAction: { flexDirection: "row", alignItems: "center", gap: 2, marginLeft: 8 },
  editText: { color: colors.crimson, fontSize: 10, fontWeight: "700" },
  divider: { height: 1, backgroundColor: "#f2f3ff", marginLeft: 64 },
  preferenceValue: { color: colors.mutedText, fontSize: 10, marginTop: 2 },
  actions: { alignItems: "center", gap: 8, paddingTop: 2 },
  logout: { width: "100%", height: 56, borderRadius: 12, borderWidth: 1, borderColor: "rgba(200,16,46,0.32)", backgroundColor: colors.surface, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, shadowColor: colors.text, shadowOpacity: 0.08, shadowRadius: 5, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  logoutText: { color: colors.crimson, fontSize: 14, fontWeight: "700" },
  deleteText: { color: colors.mutedText, fontSize: 11, paddingVertical: 4 },
  bottomTabs: { height: 64, paddingHorizontal: 8, borderTopWidth: 1, borderTopColor: "#e5e7eb", backgroundColor: "rgba(255,255,255,0.95)", flexDirection: "row", alignItems: "center" },
  tab: { flex: 1, alignItems: "center", justifyContent: "center", gap: 3 },
  tabText: { color: "#6b7280", fontSize: 10, fontWeight: "500" },
  tabActive: { color: colors.crimson, fontWeight: "700" },
});