import { StyleSheet } from "react-native";

import { colors } from "../theme/colors";

export const donorHistoryStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  screen: { flex: 1, backgroundColor: colors.background },
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 10, flexDirection: "row", alignItems: "center", gap: 10 },
  brandLogo: { width: 36, height: 36 },
  brandCopy: { flex: 1 },
  brandName: { color: colors.text, fontSize: 11, lineHeight: 13, fontWeight: "800" },
  portal: { color: colors.mutedText, fontSize: 7, lineHeight: 9, fontWeight: "700", letterSpacing: 0.9, textTransform: "uppercase" },
  content: { flex: 1 },
  scrollContent: { paddingHorizontal: 16, paddingBottom: 88 },
  heading: { paddingTop: 6, marginBottom: 18 },
  title: { color: colors.text, fontSize: 22, lineHeight: 28, fontWeight: "800" },
  subtitle: { color: colors.mutedText, fontSize: 12, lineHeight: 18, marginTop: 3 },
  filterRow: { flexDirection: "row", gap: 8, marginBottom: 16 },
  filter: { paddingHorizontal: 14, minHeight: 30, borderRadius: 999, alignItems: "center", justifyContent: "center", backgroundColor: colors.surfaceContainer ?? "#eaedff" },
  filterActive: { backgroundColor: colors.crimson },
  filterText: { color: colors.mutedText, fontSize: 11, fontWeight: "600" },
  filterTextActive: { color: colors.surface, fontWeight: "700" },
  liveHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 7 },
  liveLabel: { flexDirection: "row", alignItems: "center", gap: 6 },
  liveDotWrap: { width: 8, height: 8, alignItems: "center", justifyContent: "center" },
  liveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.crimson },
  liveDotPulse: { position: "absolute", width: 8, height: 8, borderRadius: 4, backgroundColor: colors.crimson },
  liveText: { color: colors.crimson, fontSize: 10, fontWeight: "800", letterSpacing: 1 },
  liveCount: { color: colors.mutedText, fontSize: 10, fontWeight: "600" },
  card: { padding: 14, borderRadius: 12, backgroundColor: colors.surface, shadowColor: colors.text, shadowOpacity: 0.08, shadowRadius: 5, shadowOffset: { width: 0, height: 2 }, elevation: 2, marginBottom: 18 },
  badgeRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 6, flexWrap: "wrap" },
  badgeGroup: { flexDirection: "row", alignItems: "center", gap: 6 },
  bloodBadge: { paddingHorizontal: 9, paddingVertical: 4, borderRadius: 999, backgroundColor: colors.crimsonSoft, flexDirection: "row", alignItems: "center", gap: 4 },
  bloodBadgeText: { color: colors.crimson, fontSize: 11, fontWeight: "700" },
  criticalBadge: { paddingHorizontal: 7, paddingVertical: 4, borderRadius: 999, backgroundColor: "#ffdad6" },
  criticalText: { color: "#93000a", fontSize: 10, fontWeight: "700" },
  urgentBadge: { paddingHorizontal: 7, paddingVertical: 4, borderRadius: 999, backgroundColor: colors.amberSoft },
  urgentText: { color: colors.amberText, fontSize: 10, fontWeight: "700" },
  routineBadge: { paddingHorizontal: 7, paddingVertical: 4, borderRadius: 999, backgroundColor: colors.slateSoft },
  routineText: { color: colors.mutedText, fontSize: 10, fontWeight: "700" },
  acceptedRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 9 },
  activeBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999, backgroundColor: colors.secondaryFixed ?? "#6ffbbe", flexDirection: "row", alignItems: "center", gap: 5 },
  activeDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.secondary },
  activeText: { color: colors.onSecondaryFixed ?? "#002113", fontSize: 10, fontWeight: "700" },
  cardTitle: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: "700", marginTop: 13 },
  commitmentLine: { flexDirection: "row", alignItems: "baseline", gap: 5, marginTop: 3 },
  commitmentLabel: { color: colors.text, fontSize: 11 },
  commitmentValue: { color: colors.crimson, fontSize: 14, fontWeight: "800" },
  locationBox: { marginTop: 12, padding: 10, borderRadius: 8, backgroundColor: "#f2f3ff", gap: 7 },
  locationRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "center", gap: 7 },
  locationCopy: { flex: 1 },
  locationTitle: { color: colors.text, fontSize: 11, fontWeight: "700" },
  locationSubtitle: { color: colors.mutedText, fontSize: 10, marginTop: 2 },
  arrivalStrip: { alignSelf: "center", paddingHorizontal: 9, paddingVertical: 4, borderRadius: 5, backgroundColor: "#ffddb8", flexDirection: "row", alignItems: "center", gap: 4 },
  arrivalText: { color: "#653e00", fontSize: 10, fontWeight: "700" },
  actionRow: { flexDirection: "row", gap: 8, marginTop: 12 },
  callButton: { flex: 1, height: 36, borderRadius: 8, backgroundColor: colors.crimson, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 },
  messageButton: { flex: 1, height: 36, borderRadius: 8, backgroundColor: "#e2e7ff", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 },
  callText: { color: colors.surface, fontSize: 11, fontWeight: "700" },
  messageText: { color: colors.text, fontSize: 11, fontWeight: "700" },
  cancelLink: { height: 32, alignItems: "center", justifyContent: "center" },
  cancelLinkText: { color: colors.mutedText, fontSize: 11, fontWeight: "600", textDecorationLine: "underline" },
  // The one affirmative action on a live card, so it is the only solid fill on
  // it: full-width green under the two outlined contact buttons, with the
  // destructive option demoted to a plain underlined link below.
  completeButton: { height: 42, borderRadius: 8, backgroundColor: colors.secondary, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, marginTop: 12 },
  completeText: { color: colors.surface, fontSize: 13, fontWeight: "800" },
  busy: { opacity: 0.7 },
  actionError: { flexDirection: "row", alignItems: "flex-start", gap: 7, padding: 10, borderRadius: 8, borderWidth: 1, borderColor: colors.crimsonBorder, backgroundColor: colors.crimsonSoft, marginTop: 10 },
  actionErrorText: { flex: 1, color: colors.crimson, fontSize: 11, lineHeight: 16, fontWeight: "600" },
  actionErrorDismiss: { padding: 2 },
  pastHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  pastTitle: { color: colors.text, fontSize: 15, fontWeight: "700" },
  pastCount: { color: colors.mutedText, fontSize: 10 },
  pastCard: { padding: 13, borderRadius: 12, backgroundColor: colors.surface, marginBottom: 9, shadowColor: colors.text, shadowOpacity: 0.04, shadowRadius: 3, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  pastBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 5, backgroundColor: colors.crimsonSoft, flexDirection: "row", alignItems: "center", gap: 4 },
  pastBadgeText: { color: colors.crimson, fontSize: 10, fontWeight: "700" },
  completedBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999, backgroundColor: "#d9fbe9", flexDirection: "row", alignItems: "center", gap: 4 },
  completedText: { color: colors.secondary, fontSize: 10, fontWeight: "700" },
  pastInfo: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 10 },
  pastIdentity: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12, marginTop: 13 },
  pastIdentityCopy: { flex: 1, minWidth: 0 },
  pastEyebrow: { color: colors.subtleText, fontSize: 9, fontWeight: "800", letterSpacing: 1.1 },
  pastPatient: { color: colors.text, fontSize: 16, lineHeight: 21, fontWeight: "800", marginTop: 3 },
  pastCoordinator: { color: colors.mutedText, fontSize: 11, marginTop: 4 },
  pastBloodTile: { minWidth: 62, paddingHorizontal: 8, paddingVertical: 6, borderRadius: 10, alignItems: "center", backgroundColor: colors.slateSoft, borderWidth: 1, borderColor: colors.border },
  pastBlood: { color: colors.text, fontSize: 16, fontWeight: "900" },
  pastBloodLabel: { color: colors.mutedText, fontSize: 8, fontWeight: "800", marginTop: 2 },
  pastDetailsGrid: { flexDirection: "row", gap: 8, marginTop: 12 },
  pastDetailItem: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "flex-start", gap: 6, padding: 9, borderRadius: 9, backgroundColor: colors.background, borderWidth: 1, borderColor: "#f1f5f9" },
  pastDetailCopy: { flex: 1, minWidth: 0 },
  pastDetailLabel: { color: colors.subtleText, fontSize: 9, fontWeight: "700" },
  pastDetailValue: { color: colors.text, fontSize: 10, lineHeight: 14, fontWeight: "700", marginTop: 3 },
  pastStatsRow: { flexDirection: "row", gap: 8, marginTop: 8 },
  pastStat: { flex: 1, padding: 8, borderRadius: 9, backgroundColor: colors.surface, borderWidth: 1, borderColor: "#f1f5f9" },
  pastStatValue: { color: colors.text, fontSize: 10, lineHeight: 14, fontWeight: "800", marginTop: 3 },
  requestOutcomeBox: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 10, padding: 9, borderRadius: 9, backgroundColor: colors.slateSoft, borderWidth: 1, borderColor: colors.border },
  requestOutcomeText: { color: colors.mutedText, fontSize: 10, fontWeight: "700" },
  hospital: { flex: 1, color: colors.text, fontSize: 12, fontWeight: "700" },
  donated: { color: colors.secondary, fontSize: 10, fontWeight: "700" },
  dateRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 5 },
  dateText: { color: colors.mutedText, fontSize: 10 },
  cancelledCard: { opacity: 0.8, backgroundColor: "#f2f3ff" },
  cancelledBadge: { backgroundColor: "#dae2fd" },
  cancelledBadgeText: { color: colors.mutedText },
  reason: { color: colors.mutedText, fontSize: 10, lineHeight: 15, marginTop: 8, padding: 8, borderRadius: 7, backgroundColor: colors.surface },
  reasonLabel: { color: colors.text, fontWeight: "700" },
  pastActions: { flexDirection: "row", gap: 8, marginTop: 10 },
  pastCallButton: { flex: 1, height: 34, borderRadius: 8, borderWidth: 1, borderColor: colors.crimsonBorder, backgroundColor: colors.crimsonSoft, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 },
  pastCallText: { color: colors.crimson, fontSize: 10, fontWeight: "800" },
  pastMessageButton: { flex: 1, height: 34, borderRadius: 8, backgroundColor: "#e2e7ff", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 },
  pastMessageText: { color: colors.text, fontSize: 10, fontWeight: "800" },
  loadingState: { alignItems: "center", justifyContent: "center", paddingVertical: 60, gap: 10 },
  loadingText: { color: colors.mutedText, fontSize: 12 },
  errorState: { alignItems: "center", justifyContent: "center", paddingVertical: 50 },
  errorIcon: { width: 60, height: 60, borderRadius: 30, backgroundColor: colors.crimsonSoft, alignItems: "center", justifyContent: "center" },
  errorTitle: { color: colors.text, fontSize: 16, fontWeight: "800", marginTop: 12 },
  errorText: { color: colors.mutedText, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 6, paddingHorizontal: 8 },
  retryButton: { marginTop: 16, height: 42, paddingHorizontal: 22, borderRadius: 10, backgroundColor: colors.crimson, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
  retryText: { color: colors.surface, fontSize: 13, fontWeight: "700" },
  pressed: { opacity: 0.75 },
  emptyState: { alignItems: "center", justifyContent: "center", paddingVertical: 70 },
  emptyIcon: { width: 48, height: 48, borderRadius: 24, backgroundColor: "#e2e7ff", alignItems: "center", justifyContent: "center" },
  emptyTitle: { color: colors.text, fontSize: 15, fontWeight: "700", marginTop: 10 },
  emptyText: { color: colors.mutedText, fontSize: 11, marginTop: 4 },
  bottomTabs: { height: 64, paddingHorizontal: 8, borderTopWidth: 1, borderTopColor: "#e5e7eb", backgroundColor: "rgba(255,255,255,0.95)", flexDirection: "row", alignItems: "center" },
  tab: { flex: 1, alignItems: "center", justifyContent: "center", gap: 3 },
  tabText: { color: "#6b7280", fontSize: 10, fontWeight: "500" },
  tabActive: { color: colors.crimson, fontWeight: "700" },
});