import { StyleSheet } from "react-native";

import { colors } from "../theme/colors";

export const donorHomeStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  screen: { flex: 1, backgroundColor: colors.background },
  header: { minHeight: 69, paddingHorizontal: 20, paddingTop: 12, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: "rgba(226,232,240,0.7)", flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  brand: { flexDirection: "row", alignItems: "center", gap: 10 },
  notificationButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center" },
  notificationBadge: { position: "absolute", top: 1, right: 0, minWidth: 16, height: 16, paddingHorizontal: 3, borderRadius: 8, backgroundColor: colors.crimson, alignItems: "center", justifyContent: "center" },
  notificationBadgeText: { color: colors.surface, fontSize: 9, fontWeight: "800" },
  brandName: { color: colors.text, fontSize: 18, lineHeight: 20, fontWeight: "800" },
  portalLabel: { color: colors.mutedText, fontSize: 10, lineHeight: 13, fontWeight: "700", letterSpacing: 1.2, textTransform: "uppercase" },
  content: { flex: 1, paddingHorizontal: 20, paddingTop: 16 },
  scrollContent: { paddingBottom: 104 },
  summary: { padding: 16, borderRadius: 16, borderWidth: 1, borderColor: "rgba(226,232,240,0.8)", backgroundColor: colors.surface, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  summaryCopy: { flex: 1, minWidth: 0, marginRight: 8 },
  summaryLabelRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  summaryLabel: { color: colors.mutedText, fontSize: 12, fontWeight: "500" },
  bloodBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, borderWidth: 1, borderColor: colors.crimsonBorder, backgroundColor: colors.crimsonSoft },
  bloodBadgeText: { color: colors.crimson, fontSize: 12, fontWeight: "800" },
  summaryText: { color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: "600", marginTop: 3, flexShrink: 1 },
  summaryAccent: { color: colors.crimson, fontWeight: "800" },
  locationButton: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 12, backgroundColor: colors.slateSoft, flexDirection: "row", alignItems: "center", gap: 5 },
  locationText: { color: "#475569", fontSize: 11, fontWeight: "700" },
  feedHeader: { paddingTop: 17, paddingBottom: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  feedTitle: { color: colors.mutedText, fontSize: 12, fontWeight: "800", letterSpacing: 1.1, textTransform: "uppercase" },
  sortLabel: { color: colors.mutedText, fontSize: 11, fontWeight: "600" },
  cards: { gap: 12 },
  requestCard: { padding: 16, borderRadius: 16, borderWidth: 1, borderColor: "rgba(226,232,240,0.9)", backgroundColor: colors.surface, overflow: "hidden" },
  criticalCard: { borderWidth: 2, borderColor: "rgba(254,205,211,0.9)" },
  accent: { position: "absolute", top: 0, bottom: 0, left: 0, width: 6, backgroundColor: colors.amber },
  criticalAccent: { backgroundColor: colors.crimson },
  cardInner: { paddingLeft: 2 },
  cardHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 8 },
  cardIdentity: { flex: 1, flexDirection: "row", alignItems: "flex-start", gap: 8 },
  neededBadge: { width: 48, height: 48, borderRadius: 12, borderWidth: 1, borderColor: colors.amberBorder, backgroundColor: colors.amberSoft, alignItems: "center", justifyContent: "center" },
  neededBadgeCritical: { borderColor: colors.crimsonBorder, backgroundColor: colors.crimsonSoft },
  neededType: { color: colors.amberText, fontSize: 16, lineHeight: 18, fontWeight: "800" },
  neededTypeCritical: { color: colors.crimson },
  neededLabel: { color: "#b45309", fontSize: 9, lineHeight: 11, fontWeight: "800", letterSpacing: 1, textTransform: "uppercase", marginTop: 2 },
  neededLabelCritical: { color: colors.crimson },
  cardDetails: { flex: 1 },
  badgeRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  urgencyBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, borderWidth: 1, flexDirection: "row", alignItems: "center", gap: 5 },
  criticalBadge: { borderColor: colors.crimsonBorder, backgroundColor: colors.crimsonSoft },
  urgentBadge: { borderColor: colors.amberBorder, backgroundColor: colors.amberSoft },
  urgencyDot: { width: 6, height: 6, borderRadius: 3 },
  criticalDot: { backgroundColor: colors.crimson },
  urgentDot: { backgroundColor: colors.amber },
  urgencyText: { fontSize: 11, fontWeight: "800" },
  criticalText: { color: colors.crimson },
  urgentText: { color: colors.amberText },
  verifiedBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, borderWidth: 1, borderColor: colors.emeraldBorder, backgroundColor: colors.emeraldSoft },
  verifiedText: { color: colors.emeraldText, fontSize: 11, fontWeight: "700" },
  unverifiedBadge: { borderColor: colors.amberBorder, backgroundColor: "rgba(255,251,235,0.7)" },
  unverifiedText: { color: "#b45309" },
  locationRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 7 },
  area: { color: "#334155", fontSize: 12, fontWeight: "700", flexShrink: 1 },
  distance: { color: colors.mutedText, fontSize: 12 },
  chevron: { paddingTop: 3 },
  divider: { height: 1, backgroundColor: "#f1f5f9", marginTop: 12, marginBottom: 10 },
  progressRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 5 },
  progressLabel: { color: "#475569", fontSize: 12 },
  progressValue: { color: colors.text, fontSize: 12, fontWeight: "800" },
  progressTrack: { height: 8, borderRadius: 4, backgroundColor: colors.slateSoft, overflow: "hidden" },
  progressFill: { height: "100%", borderRadius: 4, backgroundColor: colors.amber },
  progressFillCritical: { backgroundColor: colors.crimson },
  deadlineRow: { marginTop: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  deadline: { flexDirection: "row", alignItems: "center", gap: 5 },
  deadlineCritical: { color: "#be123c" },
  deadlineUrgent: { color: colors.amberText },
  deadlineText: { fontSize: 12, fontWeight: "700" },
  detailsLink: { color: colors.crimson, fontSize: 11, fontWeight: "800" },
  emptyState: { alignItems: "center", paddingHorizontal: 24, paddingTop: 52 },
  emptyIcon: { width: 64, height: 64, borderRadius: 32, borderWidth: 1, borderColor: colors.crimsonBorder, backgroundColor: "rgba(255,241,242,0.6)", alignItems: "center", justifyContent: "center" },
  emptyTitle: { color: "#1e293b", fontSize: 15, fontWeight: "800", marginTop: 12 },
  emptyText: { color: colors.mutedText, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 4 },
  bottomBar: { position: "absolute", bottom: 0, left: 0, right: 0, minHeight: 72, paddingHorizontal: 32, paddingTop: 10, paddingBottom: 10, borderTopWidth: 1, borderTopColor: "rgba(226,232,240,0.8)", backgroundColor: "rgba(255,255,255,0.96)", flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  tab: { alignItems: "center", gap: 4, minWidth: 56 },
  tabLabel: { color: "#6b7280", fontSize: 10, fontWeight: "500" },
  activeTabLabel: { color: colors.crimson, fontWeight: "800" },

  // --- Routine urgency -----------------------------------------------------
  // The feed used to be typed as "critical" | "urgent" only, which quietly
  // dropped the backend's third level. Routine gets the neutral treatment the
  // history screens already use for it.
  routineBadge: { borderColor: colors.border, backgroundColor: colors.slateSoft },
  routineDot: { backgroundColor: colors.subtleText },
  routineText: { color: colors.mutedText },
  routineAccent: { backgroundColor: "#cbd5e1" },

  // --- Feed states ---------------------------------------------------------
  loadingState: { alignItems: "center", paddingTop: 48, gap: 12 },
  loadingText: { color: colors.mutedText, fontSize: 13, fontWeight: "600" },
  errorState: { alignItems: "center", paddingHorizontal: 24, paddingTop: 40 },
  errorIcon: { width: 64, height: 64, borderRadius: 32, borderWidth: 1, borderColor: colors.crimsonBorder, backgroundColor: colors.crimsonSoft, alignItems: "center", justifyContent: "center" },
  errorTitle: { color: "#1e293b", fontSize: 15, fontWeight: "800", marginTop: 12 },
  errorText: { color: colors.mutedText, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 6 },
  errorActions: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 16 },
  retryButton: { paddingHorizontal: 18, paddingVertical: 11, borderRadius: 12, backgroundColor: colors.crimson, flexDirection: "row", alignItems: "center", gap: 6 },
  retryText: { color: "#ffffff", fontSize: 13, fontWeight: "800" },
  secondaryButton: { paddingHorizontal: 18, paddingVertical: 11, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  secondaryText: { color: "#475569", fontSize: 13, fontWeight: "700" },
  pressed: { opacity: 0.85 },
});