import { StyleSheet } from "react-native";

export const donorSignupStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#fafafb" },
  screen: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 20, paddingBottom: 32, backgroundColor: "#fafafb" },
  topBar: { height: 44, marginBottom: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  backButton: { width: 40, height: 40, borderRadius: 20, borderWidth: 1, borderColor: "#e2e8f0", backgroundColor: "#ffffff", alignItems: "center", justifyContent: "center", shadowColor: "#0f172a", shadowOpacity: 0.04, shadowRadius: 3, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  logo: { width: 48, height: 48, borderRadius: 16 },
  topBarSpacer: { width: 40, height: 40 },
  headingBlock: { marginBottom: 14 },
  title: { color: "#0f172a", fontSize: 24, lineHeight: 30, fontWeight: "700", letterSpacing: -0.5 },
  subtitle: { color: "#64748b", fontSize: 14, lineHeight: 20, marginTop: 8 },
  form: { gap: 10 },
  fieldGroup: { gap: 6 },
  label: { color: "#0f172a", fontSize: 13, lineHeight: 18, fontWeight: "600" },
  inputShell: { height: 44, paddingHorizontal: 14, borderRadius: 12, borderWidth: 1, borderColor: "#e2e8f0", backgroundColor: "#ffffff", flexDirection: "row", alignItems: "center" },
  input: { flex: 1, color: "#0f172a", fontSize: 14, marginLeft: 9, paddingVertical: 0 },
  phoneRow: { flexDirection: "row", gap: 8 },
  countrySelector: { width: 100, height: 44, borderRadius: 12, borderWidth: 1, borderColor: "#e2e8f0", backgroundColor: "#ffffff", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  flag: { fontSize: 15 },
  countryCode: { color: "#0f172a", fontSize: 14, fontWeight: "600" },
  phoneInput: { flex: 1, height: 44, paddingHorizontal: 14, borderRadius: 12, borderWidth: 1, borderColor: "#e2e8f0", backgroundColor: "#ffffff", color: "#0f172a", fontSize: 14 },
  bloodGroup: { paddingTop: 1 },
  bloodHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 8 },
  selectHint: { color: "#94a3b8", fontSize: 12 },
  bloodGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  bloodButton: { width: "23%", height: 40, borderRadius: 12, borderWidth: 1, borderColor: "#e2e8f0", backgroundColor: "#ffffff", alignItems: "center", justifyContent: "center" },
  bloodButtonSelected: { borderColor: "#c8102e", backgroundColor: "#c8102e", shadowColor: "#c8102e", shadowOpacity: 0.15, shadowRadius: 4, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  bloodButtonText: { color: "#0f172a", fontSize: 15, fontWeight: "600" },
  bloodButtonTextSelected: { color: "#ffffff" },
  passwordGroup: { paddingTop: 1 },
  strengthTrack: { height: 6, marginTop: 10, borderRadius: 3, backgroundColor: "#e2e8f0", flexDirection: "row", overflow: "hidden" },
  strengthSegment: { flex: 1, backgroundColor: "transparent", borderRightWidth: 1, borderRightColor: "#ffffff" },
  strengthMeta: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 5 },
  strengthText: { fontSize: 11, fontWeight: "500" },
  requirementText: { color: "#94a3b8", fontSize: 11 },
  bottomActions: { marginTop: 14 },
  createButton: { height: 50, borderRadius: 16, backgroundColor: "#c8102e", alignItems: "center", justifyContent: "center", shadowColor: "#c8102e", shadowOpacity: 0.28, shadowRadius: 12, shadowOffset: { width: 0, height: 7 }, elevation: 4 },
  createButtonText: { color: "#ffffff", fontSize: 16, fontWeight: "600", letterSpacing: 0.2 },
  legalText: { color: "#64748b", fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 8, paddingHorizontal: 8 },
  legalLink: { color: "#c8102e", fontWeight: "500" },
  pressed: { opacity: 0.86, transform: [{ scale: 0.99 }] },

  // --- Feedback states -----------------------------------------------------
  // Colours are the same as loginStyles so the two screens read as one product.
  inputShellError: { borderColor: "#fecdd3" },
  fieldError: { color: "#b42318", fontSize: 12, lineHeight: 16 },
  errorText: { color: "#b42318", fontSize: 13, lineHeight: 18 },
  buttonDisabled: { opacity: 0.65 },

  successCard: { marginTop: 4, padding: 18, borderRadius: 16, borderWidth: 1, borderColor: "#a7f3d0", backgroundColor: "#ecfdf5", gap: 8 },
  successHeading: { flexDirection: "row", alignItems: "center", gap: 8 },
  successTitle: { color: "#047857", fontSize: 17, fontWeight: "700" },
  successBody: { color: "#065f46", fontSize: 13, lineHeight: 19 },
  successEmail: { fontWeight: "700" },
  resendLink: { minHeight: 40, alignItems: "center", justifyContent: "center", paddingVertical: 8 },
  resendLinkText: { color: "#c8102e", fontSize: 13, fontWeight: "600" },
  resendNote: { color: "#047857", fontSize: 12, lineHeight: 16 },
});