import { StyleSheet } from "react-native";

export const loginStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#ffffff" },
  screen: { flex: 1, backgroundColor: "#ffffff" },
  topBar: { height: 56, paddingHorizontal: 24, paddingTop: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  backButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: "rgba(241, 245, 249, 0.8)", alignItems: "center", justifyContent: "center" },
  logo: { width: 48, height: 48, borderRadius: 16 },
  topBarSpacer: { width: 48, height: 48 },
  content: { flex: 1, paddingHorizontal: 24 },
  contentContainer: { paddingTop: 8, paddingBottom: 8 },
  headingBlock: { marginTop: 8, marginBottom: 12 },
  title: { color: "#0f172a", fontSize: 26, lineHeight: 32, fontWeight: "700", letterSpacing: -0.6 },
  subtitle: { color: "#64748b", fontSize: 15, lineHeight: 22, marginTop: 8 },
  form: { gap: 10 },
  groupToggle: { minHeight: 42, padding: 3, borderRadius: 14, backgroundColor: "#f1f5f9", flexDirection: "row", gap: 3 },
  groupOption: { flex: 1, minHeight: 40, paddingHorizontal: 8, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  groupOptionActive: { backgroundColor: "#ffffff", shadowColor: "#0f172a", shadowOpacity: 0.08, shadowRadius: 4, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  groupOptionText: { color: "#64748b", fontSize: 12, lineHeight: 16, fontWeight: "600", textAlign: "center" },
  groupOptionTextActive: { color: "#c8102e" },
  roleSelector: { flexDirection: "row", gap: 10 },
  roleOption: { flex: 1, minHeight: 52, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 12, borderWidth: 1, borderColor: "#e2e8f0", backgroundColor: "#ffffff" },
  roleOptionActive: { borderColor: "#c8102e", backgroundColor: "#fff7f7" },
  roleLabel: { color: "#334155", fontSize: 14, lineHeight: 18, fontWeight: "700" },
  roleLabelActive: { color: "#c8102e" },
  roleDescription: { color: "#64748b", fontSize: 10, lineHeight: 14, marginTop: 3 },
  fieldGroup: { gap: 6 },
  label: { color: "#334155", fontSize: 14, lineHeight: 20, fontWeight: "500" },
  inputShell: { height: 46, paddingHorizontal: 14, borderRadius: 12, borderWidth: 1, borderColor: "#e2e8f0", backgroundColor: "#f8fafc", flexDirection: "row", alignItems: "center" },
  input: { flex: 1, color: "#0f172a", fontSize: 15, marginLeft: 10, paddingVertical: 0 },
  passwordInput: { flex: 1, color: "#0f172a", fontSize: 15, paddingVertical: 0 },
  forgotButton: { alignSelf: "flex-end", marginTop: 4 },
  forgotText: { color: "#c8102e", fontSize: 14, lineHeight: 20, fontWeight: "500" },
  forgotTextDisabled: { color: "#94a3b8" },
  forgotNote: { color: "#64748b", fontSize: 11, lineHeight: 16, textAlign: "right", marginTop: 2 },
  loginButton: { height: 50, borderRadius: 16, backgroundColor: "#c8102e", alignItems: "center", justifyContent: "center", marginTop: 8, shadowColor: "#c8102e", shadowOpacity: 0.25, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 4 },
  loginButtonText: { color: "#ffffff", fontSize: 16, lineHeight: 20, fontWeight: "700" },
  loginButtonDisabled: { opacity: 0.65 },
  errorText: { color: "#b42318", fontSize: 13, lineHeight: 18, marginTop: -8 },
  socialSection: { marginTop: 10, gap: 8 },
  dividerRow: { height: 16, alignItems: "center", justifyContent: "center", flexDirection: "row" },
  divider: { flex: 1, height: 1, backgroundColor: "#e2e8f0" },
  orText: { color: "#64748b", backgroundColor: "#ffffff", paddingHorizontal: 12, fontSize: 10, lineHeight: 14, fontWeight: "500", letterSpacing: 1.2 },
  socialButton: { height: 44, borderRadius: 12, borderWidth: 1, borderColor: "#e2e8f0", backgroundColor: "#ffffff", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10, shadowColor: "#0f172a", shadowOpacity: 0.03, shadowRadius: 3, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  googleLogo: { width: 16, height: 16 },
  googleText: { color: "#1e293b", fontSize: 14, lineHeight: 20, fontWeight: "500" },
  appleButton: { height: 44, borderRadius: 12, backgroundColor: "#000000", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10 },
  appleText: { color: "#ffffff", fontSize: 14, lineHeight: 20, fontWeight: "500" },
  signupPrompt: { alignItems: "center", marginTop: 8, paddingBottom: 8 },
  signupText: { color: "#475569", fontSize: 14, lineHeight: 20 },
  signupLink: { color: "#c8102e", fontWeight: "600" },
  signupLinkDisabled: { color: "#94a3b8" },
  signupNote: { color: "#64748b", fontSize: 12, lineHeight: 17, textAlign: "center", marginTop: 4 },
  pressed: { opacity: 0.85, transform: [{ scale: 0.99 }] },

  // --- Resend verification -------------------------------------------------
  // Sits under the sign-up prompt rather than in the form, so it never competes
  // with the primary Log In button.
  resendPrompt: { alignItems: "center", marginTop: 2, paddingBottom: 4 },
  resendButton: { minHeight: 36, alignItems: "center", justifyContent: "center", paddingHorizontal: 8 },
  resendText: { color: "#475569", fontSize: 13, lineHeight: 18, fontWeight: "500" },
  resendNote: { color: "#047857", fontSize: 12, lineHeight: 16, marginTop: 2, textAlign: "center" },
  resendError: { color: "#b42318", fontSize: 12, lineHeight: 16, marginTop: 2, textAlign: "center" },
});