import { StyleSheet } from "react-native";

import { colors } from "../theme/colors";

export const notificationInboxStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  screen: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    backgroundColor: colors.surface,
  },
  backButton: { width: 36, height: 36, borderRadius: 18, backgroundColor: colors.slateSoft, alignItems: "center", justifyContent: "center" },
  headerText: { flex: 1, marginLeft: 12 },
  title: { color: colors.text, fontSize: 18, fontWeight: "800" },
  subtitle: { color: colors.mutedText, fontSize: 11, fontWeight: "600", marginTop: 2 },
  markAllButton: { minHeight: 36, paddingHorizontal: 8, alignItems: "center", justifyContent: "center" },
  markAllText: { color: colors.crimson, fontSize: 11, fontWeight: "800" },
  content: { flex: 1 },
  list: { flexGrow: 1, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 22 },
  loadingState: { alignItems: "center", paddingTop: 56, gap: 12 },
  loadingText: { color: colors.mutedText, fontSize: 13, fontWeight: "600" },
  errorState: { alignItems: "center", paddingHorizontal: 24, paddingTop: 52 },
  errorIcon: { width: 64, height: 64, borderRadius: 32, borderWidth: 1, borderColor: colors.crimsonBorder, backgroundColor: colors.crimsonSoft, alignItems: "center", justifyContent: "center" },
  errorTitle: { color: colors.text, fontSize: 16, fontWeight: "800", marginTop: 12 },
  errorText: { color: colors.mutedText, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 6 },
  retryButton: { marginTop: 18, flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: colors.crimson, paddingHorizontal: 18, paddingVertical: 11, borderRadius: 12 },
  retryText: { color: colors.surface, fontSize: 13, fontWeight: "700" },
  pressed: { opacity: 0.85 },
  emptyState: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 30, paddingTop: 52 },
  emptyIcon: { width: 68, height: 68, borderRadius: 34, backgroundColor: colors.surface, borderWidth: 1, borderColor: "#e2e8f0", alignItems: "center", justifyContent: "center" },
  emptyTitle: { color: colors.text, fontSize: 16, fontWeight: "700", marginTop: 12 },
  emptyText: { color: colors.mutedText, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 6 },
  row: { flexDirection: "row", alignItems: "flex-start", gap: 12, backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: "#e2e8f0", paddingHorizontal: 12, paddingVertical: 13, marginBottom: 12 },
  unreadRow: { backgroundColor: colors.crimsonSoft, borderColor: colors.crimsonBorder },
  iconWrap: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.slateSoft, alignItems: "center", justifyContent: "center" },
  unreadIconWrap: { backgroundColor: colors.surface },
  rowBody: { flex: 1, minWidth: 0 },
  rowHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 8 },
  rowTitle: { flex: 1, color: colors.text, fontSize: 14, fontWeight: "800" },
  unreadTitle: { color: colors.crimson },
  rowTime: { color: colors.mutedText, fontSize: 10, fontWeight: "600" },
  rowBodyText: { color: colors.mutedText, fontSize: 12, lineHeight: 18, marginTop: 5 },
  unreadBody: { color: colors.text },
  unreadDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.crimson, marginTop: 5 },
});
