import { StyleSheet } from "react-native";

import { colors } from "../theme/colors";

export const requestDetailStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  screen: { flex: 1, backgroundColor: colors.background },
  scroll: { paddingHorizontal: 16, paddingBottom: 154 },
  header: { height: 58, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  backButton: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" },
  headerCenter: { alignItems: "center" },
  title: { color: colors.text, fontSize: 17, lineHeight: 21, fontWeight: "700" },
  subtitle: { color: colors.crimson, fontSize: 11, lineHeight: 14, fontWeight: "700", letterSpacing: 1.1, textTransform: "uppercase" },
  headerSpacer: { width: 40, height: 40 },
  urgency: { padding: 14, borderRadius: 16, backgroundColor: "#fff0f2", borderWidth: 1, borderColor: "#ffe0e4", marginBottom: 12 },
  urgencyTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 6 },
  urgencyLabel: { flexDirection: "row", alignItems: "center", gap: 8 },
  urgencyDotWrap: { width: 10, height: 10, alignItems: "center", justifyContent: "center" },
  urgencyPulse: { position: "absolute", width: 10, height: 10, borderRadius: 5, backgroundColor: colors.crimson },
  urgencyDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.crimson },
  urgencyText: { color: colors.crimson, fontSize: 13, fontWeight: "800", letterSpacing: 1.1 },
  dispatchTag: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 999, borderWidth: 1, borderColor: "rgba(200,16,46,0.1)", backgroundColor: colors.surface, color: colors.crimson, fontSize: 11, fontWeight: "700" },
  countdown: { flexDirection: "row", alignItems: "center", gap: 6 },
  countdownText: { color: colors.crimson, fontSize: 13, fontWeight: "700" },

  // --- Urgency variants ----------------------------------------------------
  // The banner was hardcoded critical-pink regardless of the request's actual
  // urgency, and urgency is a three-value field. The base styles above are the
  // critical ones; these override for the two calmer levels.
  urgencyUrgent: { backgroundColor: colors.amberSoft, borderColor: colors.amberBorder },
  urgencyRoutine: { backgroundColor: colors.slateSoft, borderColor: colors.border },
  urgencyDotUrgent: { backgroundColor: colors.amber },
  urgencyDotRoutine: { backgroundColor: colors.subtleText },
  urgencyTextUrgent: { color: colors.amberText },
  urgencyTextRoutine: { color: colors.mutedText },
  dispatchTagUrgent: { color: colors.amberText, borderColor: colors.amberBorder },
  dispatchTagRoutine: { color: colors.mutedText, borderColor: colors.border },
  countdownTextUrgent: { color: colors.amberText },
  countdownTextRoutine: { color: colors.mutedText },
  hero: { padding: 20, borderRadius: 16, backgroundColor: colors.surface, alignItems: "center", marginBottom: 12 },
  bloodCircle: { width: 80, height: 80, borderRadius: 40, borderWidth: 1, borderColor: "#fecaca", backgroundColor: "#fef2f2", alignItems: "center", justifyContent: "center", marginBottom: 12 },
  bloodType: { color: colors.crimson, fontSize: 32, lineHeight: 35, fontWeight: "900" },
  bloodNeeded: { color: colors.crimson, fontSize: 10, lineHeight: 13, fontWeight: "800", letterSpacing: 1.5 },
  verifiedBadge: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 999, borderWidth: 1, borderColor: colors.emeraldBorder, backgroundColor: colors.emeraldSoft, flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 10 },
  verifiedText: { color: colors.emeraldText, fontSize: 12, fontWeight: "700" },
  unverifiedBadge: { borderColor: colors.amberBorder, backgroundColor: colors.amberSoft },
  unverifiedText: { color: colors.amberText },
  requestTitle: { color: colors.text, fontSize: 19, lineHeight: 24, fontWeight: "700", letterSpacing: -0.3 },
  // --- Where it is ---------------------------------------------------------
  // This used to be a MapView pinned to coordinates the mock invented. The
  // backend sends no coordinates for a request — BloodRequestOut has no
  // latitude/longitude, and the nearby listing has no distance either — so
  // there is nothing honest to plot. The area and the radius it is currently
  // searching are real, and are what the donor needs to judge the trip.
  areaCard: { padding: 16, borderRadius: 16, borderWidth: 1, borderColor: "#e2e8f0", backgroundColor: colors.surface, marginBottom: 12 },
  areaRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  areaIconWrap: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.crimsonSoft, alignItems: "center", justifyContent: "center" },
  areaCopy: { flex: 1, minWidth: 0 },
  areaTitle: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: "700" },
  areaSub: { color: colors.mutedText, fontSize: 12, lineHeight: 17, marginTop: 2 },
  distanceChip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999, borderWidth: 1, borderColor: colors.crimsonBorder, backgroundColor: colors.crimsonSoft, flexDirection: "row", alignItems: "center", gap: 4 },
  distanceChipText: { color: colors.crimson, fontSize: 11, fontWeight: "700" },
  card: { padding: 16, borderRadius: 16, backgroundColor: colors.surface, marginBottom: 12 },
  sectionHeading: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: "700", marginBottom: 12 },
  rowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 8 },
  muted: { color: colors.mutedText, fontSize: 14, fontWeight: "500" },
  strong: { color: colors.text, fontSize: 14, fontWeight: "700" },
  progressTrack: { height: 10, borderRadius: 5, backgroundColor: "#fee2e2", overflow: "hidden", marginBottom: 9 },
  progressFill: { height: "100%", borderRadius: 5, backgroundColor: colors.crimson },
  progressFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  progressMessage: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 5 },
  crimsonSmall: { flexShrink: 1, color: colors.crimson, fontSize: 12, lineHeight: 16, fontWeight: "700" },
  completion: { flexShrink: 0, marginLeft: 10, color: colors.mutedText, fontSize: 12, fontWeight: "500" },
  logisticsRow: { flexDirection: "row", alignItems: "flex-start", gap: 12, marginBottom: 14 },
  logisticsIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: "#f4f5fa", alignItems: "center", justifyContent: "center" },
  logisticsCopy: { flex: 1, minWidth: 0, paddingTop: 1 },
  logisticsTitle: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: "600" },
  logisticsSub: { color: colors.mutedText, fontSize: 12, lineHeight: 17, marginTop: 2 },
  reassurance: { padding: 14, borderRadius: 16, borderWidth: 1, borderColor: "#e4ecfb", backgroundColor: "#f8faff", flexDirection: "row", alignItems: "flex-start", gap: 12, marginBottom: 12 },
  reassuranceIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center" },
  reassuranceCopy: { flex: 1 },
  reassuranceTitle: { color: colors.text, fontSize: 13, lineHeight: 17, fontWeight: "600" },
  reassuranceText: { color: colors.mutedText, fontSize: 11, lineHeight: 16, marginTop: 4 },
  precheck: { padding: 16, borderRadius: 16, backgroundColor: colors.surface },
  precheckRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  precheckText: { color: colors.text, fontSize: 13, fontWeight: "500" },
  bottomAction: { position: "absolute", left: 0, right: 0, bottom: 56, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 10, borderTopWidth: 1, borderTopColor: "#f1f5f9", backgroundColor: "rgba(255,255,255,0.96)" },
  acceptButton: { height: 52, borderRadius: 12, backgroundColor: colors.crimson, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 },
  acceptText: { color: colors.surface, fontSize: 15, fontWeight: "700" },
  commitmentText: { color: colors.mutedText, fontSize: 11, textAlign: "center", marginTop: 7 },
  bottomTabs: { position: "absolute", left: 0, right: 0, bottom: 0, height: 56, paddingHorizontal: 8, borderTopWidth: 1, borderTopColor: "#f1f5f9", backgroundColor: colors.surface, flexDirection: "row", alignItems: "center" },
  tab: { flex: 1, alignItems: "center", justifyContent: "center", gap: 3 },
  tabText: { color: "#6b7280", fontSize: 11, fontWeight: "600" },
  tabActive: { color: colors.crimson },
  modalBackdrop: { flex: 1, backgroundColor: "rgba(15,23,42,0.45)", justifyContent: "flex-end" },
  modal: { width: "100%", maxHeight: "90%", borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: colors.surface, overflow: "hidden" },
  modalHandle: { width: 48, height: 6, borderRadius: 3, backgroundColor: "#cbd5e1", alignSelf: "center", marginTop: 12, marginBottom: 12 },
  modalClose: { position: "absolute", top: 14, right: 16, width: 32, height: 32, borderRadius: 16, backgroundColor: colors.slateSoft, alignItems: "center", justifyContent: "center", zIndex: 1 },
  modalContent: { paddingHorizontal: 20, paddingTop: 2, paddingBottom: 24 },
  modalHeader: { paddingRight: 32, marginBottom: 14 },
  modalTitle: { color: colors.text, fontSize: 20, lineHeight: 25, fontWeight: "700", letterSpacing: -0.3 },
  modalBody: { color: colors.mutedText, fontSize: 13, lineHeight: 18, marginTop: 2 },
  commitmentPill: { alignSelf: "flex-start", paddingHorizontal: 12, paddingVertical: 5, borderRadius: 999, borderWidth: 1, borderColor: "#ffe2e6", backgroundColor: colors.crimsonSoft, flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 16 },
  commitmentPillDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.crimson },
  commitmentPillText: { color: colors.crimson, fontSize: 12, fontWeight: "700" },
  unitsBox: { padding: 14, borderRadius: 16, borderWidth: 1, borderColor: "#f1f5f9", backgroundColor: "#f8fafc", flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 16 },
  unitsCopy: { flex: 1, paddingRight: 8 },
  unitsTitle: { color: colors.text, fontSize: 13, lineHeight: 17, fontWeight: "700" },
  unitsSubtitle: { color: colors.mutedText, fontSize: 11, lineHeight: 15, marginTop: 2 },
  stepper: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, borderWidth: 1, borderColor: "#e2e8f0", backgroundColor: colors.surface, flexDirection: "row", alignItems: "center", gap: 8 },
  stepperButton: { width: 28, height: 28, borderRadius: 9, backgroundColor: colors.slateSoft, alignItems: "center", justifyContent: "center" },
  stepperButtonDisabled: { opacity: 0.7 },
  stepperValue: { minWidth: 18, color: colors.text, fontSize: 15, fontWeight: "800", textAlign: "center" },
  arrivalTitle: { color: colors.text, fontSize: 13, fontWeight: "700", marginBottom: 8 },
  arrivalGrid: { flexDirection: "row", gap: 8, marginBottom: 16 },
  arrivalOption: { flex: 1, minHeight: 38, borderRadius: 12, borderWidth: 1, borderColor: "#e2e8f0", alignItems: "center", justifyContent: "center" },
  arrivalOptionSelected: { borderColor: colors.crimson, backgroundColor: colors.crimson, shadowColor: colors.crimson, shadowOpacity: 0.18, shadowRadius: 4, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  arrivalText: { color: "#475569", fontSize: 12, fontWeight: "500" },
  arrivalTextSelected: { color: colors.surface, fontWeight: "700" },
  reminderBox: { padding: 12, borderRadius: 12, borderWidth: 1, borderColor: "#ffe4e7", backgroundColor: "#fff5f6", flexDirection: "row", alignItems: "flex-start", gap: 10, marginBottom: 18 },
  reminderIcon: { width: 24, height: 24, borderRadius: 12, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center" },
  reminderText: { flex: 1, color: "#334155", fontSize: 12, lineHeight: 17, paddingTop: 2 },
  modalActions: { gap: 8 },
  modalCancel: { height: 32, alignItems: "center", justifyContent: "center" },
  modalConfirm: { width: "100%", height: 48, borderRadius: 12, backgroundColor: colors.crimson, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 6, shadowColor: colors.crimson, shadowOpacity: 0.2, shadowRadius: 6, shadowOffset: { width: 0, height: 3 }, elevation: 3 },
  modalCancelText: { color: colors.mutedText, fontSize: 13, fontWeight: "500" },
  modalConfirmText: { color: colors.surface, fontSize: 15, fontWeight: "700", letterSpacing: 0.2 },

  // --- Fetch states --------------------------------------------------------
  loadingState: { alignItems: "center", paddingTop: 96, gap: 12 },
  loadingText: { color: colors.mutedText, fontSize: 13, fontWeight: "600" },
  errorState: { alignItems: "center", paddingHorizontal: 24, paddingTop: 80 },
  errorIcon: { width: 64, height: 64, borderRadius: 32, borderWidth: 1, borderColor: colors.crimsonBorder, backgroundColor: colors.crimsonSoft, alignItems: "center", justifyContent: "center" },
  errorTitle: { color: "#1e293b", fontSize: 16, fontWeight: "800", marginTop: 12, textAlign: "center" },
  errorText: { color: colors.mutedText, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 6 },
  errorActions: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 18 },
  retryButton: { paddingHorizontal: 18, paddingVertical: 11, borderRadius: 12, backgroundColor: colors.crimson, flexDirection: "row", alignItems: "center", gap: 6 },
  retryText: { color: colors.surface, fontSize: 13, fontWeight: "800" },
  pressed: { opacity: 0.85 },

  // --- Accept failures -----------------------------------------------------
  modalError: { padding: 12, borderRadius: 12, borderWidth: 1, borderColor: colors.crimsonBorder, backgroundColor: colors.crimsonSoft, flexDirection: "row", alignItems: "flex-start", gap: 8, marginBottom: 12 },
  modalErrorText: { flex: 1, color: "#b42318", fontSize: 12, lineHeight: 17, fontWeight: "600" },
  availableButton: { height: 40, borderRadius: 12, borderWidth: 1, borderColor: colors.emeraldBorder, backgroundColor: colors.emeraldSoft, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 6, marginBottom: 10 },
  availableButtonText: { color: colors.emeraldText, fontSize: 13, fontWeight: "700" },
  modalConfirmBusy: { opacity: 0.7 },

  // --- Commitment confirmed ------------------------------------------------
  // Shown in the same sheet once the backend has recorded the match, so the
  // donor gets the coordinator's number instead of being bounced away from a
  // screen whose numbers are now stale.
  successBox: { alignItems: "center", paddingTop: 4 },
  successIcon: { width: 72, height: 72, borderRadius: 36, borderWidth: 1, borderColor: colors.emeraldBorder, backgroundColor: colors.emeraldSoft, alignItems: "center", justifyContent: "center" },
  successTitle: { color: colors.text, fontSize: 20, lineHeight: 25, fontWeight: "800", marginTop: 12, textAlign: "center", letterSpacing: -0.3 },
  successText: { color: colors.mutedText, fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 6 },
  successRows: { alignSelf: "stretch", marginTop: 18, padding: 14, borderRadius: 16, borderWidth: 1, borderColor: "#f1f5f9", backgroundColor: "#f8fafc", gap: 10 },
  successRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  successLabel: { color: colors.mutedText, fontSize: 12 },
  successValue: { flexShrink: 1, color: colors.text, fontSize: 13, fontWeight: "700", textAlign: "right" },
  coordinatorBox: { alignSelf: "stretch", marginTop: 12, padding: 14, borderRadius: 16, borderWidth: 1, borderColor: "#e4ecfb", backgroundColor: "#f8faff", flexDirection: "row", alignItems: "center", gap: 12 },
  coordinatorCopy: { flex: 1, minWidth: 0 },
  coordinatorLabel: { color: colors.mutedText, fontSize: 11, fontWeight: "700", letterSpacing: 0.8, textTransform: "uppercase" },
  coordinatorName: { color: colors.text, fontSize: 14, fontWeight: "700", marginTop: 2 },
  coordinatorPhone: { color: colors.mutedText, fontSize: 12, marginTop: 2 },
  callButton: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: 11, backgroundColor: colors.crimson, flexDirection: "row", alignItems: "center", gap: 5 },
  callText: { color: colors.surface, fontSize: 12, fontWeight: "800" },
});