import { StyleSheet } from "react-native";

import { colors } from "../theme/colors";

export const requestorProfileStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  screen: { flex: 1, backgroundColor: colors.background },
  header: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 12,
    backgroundColor: "rgba(250,248,255,0.96)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(148,163,184,0.25)",
  },
  logo: { width: 32, height: 32 },
  brandWrap: { flexDirection: "row", alignItems: "center", gap: 10 },
  brandCopy: { justifyContent: "center" },
  brand: { color: colors.text, fontSize: 16, fontWeight: "700", letterSpacing: -0.2 },
  portal: { color: colors.mutedText, fontSize: 9, fontWeight: "800", letterSpacing: 1.1, textTransform: "uppercase", marginTop: 2 },
  scrollContent: { paddingBottom: 88, paddingHorizontal: 16, paddingTop: 18 },
  profileHeader: { alignItems: "center", justifyContent: "center", paddingBottom: 8 },
  avatarWrap: { position: "relative", marginBottom: 14 },
  avatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: "#ffe4e6",
    borderWidth: 4,
    borderColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.text,
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  avatarText: { color: colors.crimson, fontSize: 24, fontWeight: "700" },
  // Absolute insets rather than a fixed size: the parent's 4px ring insets the
  // content box, so this fills the circle inside it without hard-coding 88.
  avatarImage: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, borderRadius: 48 },
  avatarBusy: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, borderRadius: 48, backgroundColor: "rgba(15,23,42,0.45)", alignItems: "center", justifyContent: "center" },
  photoError: { color: colors.crimson, fontSize: 11, lineHeight: 16, fontWeight: "600", textAlign: "center", marginTop: 8, paddingHorizontal: 12, marginBottom: 4 },
  cameraButton: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.crimson,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.surface,
  },
  nameRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  name: { color: colors.text, fontSize: 22, fontWeight: "700", letterSpacing: -0.3 },
  nameEditButton: { padding: 4 },
  section: { marginTop: 18 },
  sectionLabel: {
    color: colors.mutedText,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.1,
    textTransform: "uppercase",
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  sectionCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    overflow: "hidden",
    shadowColor: colors.text,
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  row: {
    minHeight: 62,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rowInner: { flex: 1, flexDirection: "row", alignItems: "center", minWidth: 0, gap: 12 },
  rowIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
  },
  rowCopy: { flex: 1, minWidth: 0 },
  rowLabel: { color: colors.mutedText, fontSize: 10, fontWeight: "500", marginBottom: 3 },
  rowValue: { color: colors.text, fontSize: 13, fontWeight: "600", flexShrink: 1 },
  rowSubtitle: { color: colors.mutedText, fontSize: 11, marginTop: 3 },
  rowAction: { flexDirection: "row", alignItems: "center", gap: 4, marginLeft: 10 },
  editText: { color: colors.crimson, fontSize: 11, fontWeight: "700" },
  divider: { height: 1, backgroundColor: "#f1f5f9", marginLeft: 58 },
  actions: { marginTop: 18, gap: 10 },
  logoutButton: {
    width: "100%",
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(200,16,46,0.32)",
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: colors.text,
    shadowOpacity: 0.06,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  logoutText: { color: colors.crimson, fontSize: 15, fontWeight: "700" },
  deleteAccountWrap: { alignItems: "center", paddingTop: 4 },
  deleteAccountText: { color: colors.mutedText, fontSize: 12, fontWeight: "500" },
  bottomTabs: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 64,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    backgroundColor: "rgba(255,255,255,0.96)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
  },
  tab: { width: 80, alignItems: "center", justifyContent: "center", gap: 3 },
  tabText: { color: "#94a3b8", fontSize: 11, fontWeight: "500" },
  tabTextActive: { color: colors.crimson, fontWeight: "700" },
});
