import { StyleSheet } from "react-native";
import { colors } from "../theme/colors";

export const requestorHistoryStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  screen: { flex: 1, backgroundColor: colors.background },
  header: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: "#e2e8f0", flexDirection: "row", alignItems: "center", gap: 10 },
  logo: { width: 40, height: 40 },
  brandCopy: { flex: 1 },
  brand: { color: colors.text, fontSize: 18, fontWeight: "700" },
  portal: { color: colors.subtleText, fontSize: 9, letterSpacing: 1.2, fontWeight: "800", marginTop: 3 },
  records: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999, backgroundColor: colors.slateSoft, borderWidth: 1, borderColor: colors.border },
  recordsText: { color: "#475569", fontSize: 11, fontWeight: "700" },
  content: { flex: 1 },
  scroll: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 88 },
  title: { color: colors.text, fontSize: 21, fontWeight: "800" },
  subtitle: { color: colors.mutedText, fontSize: 12, marginTop: 3, marginBottom: 16 },
  filters: { flexDirection: "row", gap: 8, marginBottom: 18 },
  filter: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 999, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  filterActive: { backgroundColor: colors.crimson, borderColor: colors.crimson },
  filterText: { color: "#475569", fontSize: 11, fontWeight: "600" },
  filterTextActive: { color: colors.surface, fontWeight: "800" },
  card: { padding: 14, borderRadius: 16, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, marginBottom: 14, overflow: "hidden" },
  accent: { height: 4, margin: -14, marginBottom: 12 },
  accentCritical: { backgroundColor: colors.crimson },
  accentUrgent: { backgroundColor: colors.amber },
  accentNeutral: { backgroundColor: "#cbd5e1" },
  badgeRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginBottom: 12 },
  badge: { paddingHorizontal: 9, paddingVertical: 4, borderRadius: 999, borderWidth: 1 },
  critical: { backgroundColor: colors.crimsonSoft, borderColor: colors.crimsonBorder },
  urgent: { backgroundColor: colors.amberSoft, borderColor: colors.amberBorder },
  routine: { backgroundColor: colors.slateSoft, borderColor: colors.border },
  statusAmber: { backgroundColor: colors.amberSoft, borderColor: colors.amberBorder },
  statusBlue: { backgroundColor: "#eff6ff", borderColor: "#bfdbfe" },
  statusGreen: { backgroundColor: colors.emeraldSoft, borderColor: colors.emeraldBorder },
  statusRose: { backgroundColor: "#fff1f2", borderColor: "#fecdd3" },
  badgeText: { color: colors.crimson, fontSize: 10, fontWeight: "800" },
  criticalText: { color: colors.crimson },
  amberText: { color: colors.amberText },
  slateText: { color: colors.mutedText },
  blueText: { color: "#1d4ed8" },
  verified: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999, backgroundColor: colors.emeraldSoft, borderWidth: 1, borderColor: colors.emeraldBorder },
  verifiedText: { color: colors.emeraldText, fontSize: 10, fontWeight: "700" },
  emeraldText: { color: colors.emeraldText },
  cancelledText: { color: "#be123c" },
  patientRow: { flexDirection: "row", justifyContent: "space-between", gap: 10, marginBottom: 12 },
  patientCopy: { flex: 1 },
  eyebrow: { color: colors.subtleText, fontSize: 9, fontWeight: "800", letterSpacing: 1.1 },
  patient: { color: colors.text, fontSize: 16, fontWeight: "800", marginTop: 3 },
  hospital: { color: "#475569", fontSize: 11 },
  hospitalRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 4 },
  bloodBox: { width: 56, height: 56, borderRadius: 12, backgroundColor: colors.crimsonSoft, borderWidth: 1, borderColor: colors.crimsonBorder, alignItems: "center", justifyContent: "center" },
  bloodAmber: { backgroundColor: colors.amberSoft, borderColor: colors.amberBorder },
  bloodNeutral: { backgroundColor: colors.slateSoft, borderColor: colors.border },
  blood: { color: colors.crimson, fontSize: 16, fontWeight: "900" },
  bloodLabel: { color: colors.crimson, fontSize: 8, fontWeight: "800", marginTop: 2 },
  progressBox: { padding: 11, borderRadius: 12, backgroundColor: "#f8fafc", borderWidth: 1, borderColor: "#f1f5f9", marginBottom: 12 },
  summaryBox: { padding: 11, borderRadius: 12, backgroundColor: "#f8fafc", borderWidth: 1, borderColor: "#e2e8f0", marginBottom: 12 },
  summaryHeader: { flexDirection: "row", alignItems: "center", gap: 9 },
  outcomeIcon: { width: 28, height: 28, borderRadius: 14, alignItems: "center", justifyContent: "center", borderWidth: 1 },
  outcomeIconNeutral: { backgroundColor: colors.slateSoft, borderColor: colors.border },
  outcomeIconBlue: { backgroundColor: "#dbeafe", borderColor: "#bfdbfe" },
  outcomeIconGreen: { backgroundColor: "#d1fae5", borderColor: colors.emeraldBorder },
  outcomeIconAmber: { backgroundColor: "#fef3c7", borderColor: colors.amberBorder },
  outcomeIconRose: { backgroundColor: "#ffe4e6", borderColor: "#fecdd3" },
  outcomeCopy: { flex: 1, minWidth: 0 },
  reason: { color: "#475569", fontSize: 11, lineHeight: 16, marginTop: 8 },
  rowBetween: { flexDirection: "row", justifyContent: "space-between" },
  label: { color: colors.mutedText, fontSize: 11 },
  value: { color: colors.crimson, fontSize: 11, fontWeight: "800" },
  track: { height: 8, borderRadius: 4, backgroundColor: "#e2e8f0", overflow: "hidden", marginTop: 6, marginBottom: 6 },
  fill: { height: "100%", backgroundColor: colors.crimson, borderRadius: 4 },
  fillAmber: { backgroundColor: colors.amber },
  meta: { color: colors.mutedText, fontSize: 10 },
  metaAccent: { color: colors.amberText, fontSize: 10, fontWeight: "700" },
  logistics: { flexDirection: "row", gap: 8, marginBottom: 12 },
  logisticsItem: { flex: 1, padding: 9, borderRadius: 10, backgroundColor: colors.background, borderWidth: 1, borderColor: "#f1f5f9" },
  logisticsCritical: { backgroundColor: colors.crimsonSoft, borderColor: colors.crimsonBorder },
  logisticsLabel: { color: colors.subtleText, fontSize: 9, fontWeight: "700" },
  logisticsValue: { color: colors.text, fontSize: 10, fontWeight: "800", marginTop: 3 },
  footer: { paddingTop: 10, borderTopWidth: 1, borderTopColor: "#f1f5f9", flexDirection: "row", justifyContent: "space-between" },
  posted: { color: colors.subtleText, fontSize: 10 },
  action: { color: colors.crimson, fontSize: 10, fontWeight: "800" },
  loadingState: { alignItems: "center", paddingVertical: 60, gap: 10 },
  loadingText: { color: colors.mutedText, fontSize: 12 },
  errorState: { alignItems: "center", paddingVertical: 52 },
  errorIcon: { width: 56, height: 56, borderRadius: 20, backgroundColor: colors.crimsonSoft, borderWidth: 1, borderColor: colors.crimsonBorder, alignItems: "center", justifyContent: "center" },
  errorTitle: { color: colors.text, fontSize: 16, fontWeight: "800", marginTop: 12 },
  errorText: { color: colors.mutedText, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 6 },
  retryButton: { marginTop: 16, height: 42, paddingHorizontal: 20, borderRadius: 10, backgroundColor: colors.crimson, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
  retryText: { color: colors.surface, fontSize: 13, fontWeight: "700" },
  pressed: { opacity: 0.75 },
  empty: { alignItems: "center", paddingVertical: 70 },
  emptyIcon: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.slateSoft, alignItems: "center", justifyContent: "center" },
  emptyTitle: { color: colors.text, fontSize: 15, fontWeight: "800", marginTop: 10 },
  emptyText: { color: colors.mutedText, fontSize: 11, marginTop: 4 },
  bottom: { height: 64, borderTopWidth: 1, borderTopColor: "#e5e7eb", backgroundColor: "rgba(255,255,255,0.95)", flexDirection: "row", alignItems: "center" },
  tab: { flex: 1, alignItems: "center", gap: 3 },
  tabText: { color: "#6b7280", fontSize: 10 },
  tabActive: { color: colors.crimson, fontWeight: "700" },
});
