import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#faf8ff" },
  container: { flex: 1, paddingHorizontal: 13, paddingTop: 4, paddingBottom: 11 },
  brandRow: { height: 56, flexDirection: "row", alignItems: "center", paddingHorizontal: 1 },
  brandLogo: { width: 48, height: 48, borderRadius: 16, marginRight: 8 },
  brandName: { color: "#131b2e", fontSize: 18, lineHeight: 24, fontWeight: "600" },
  onlineDot: { width: 8, height: 8, borderRadius: 4, marginLeft: 6, alignItems: "center", justifyContent: "center" },
  onlineDotPulse: { position: "absolute", width: 8, height: 8, borderRadius: 4, backgroundColor: "#6ffbbe" },
  onlineDotCore: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#006c49" },
  hero: { height: 224, borderRadius: 24, overflow: "hidden", alignItems: "center", justifyContent: "center", shadowColor: "#131b2e", shadowOpacity: 0.05, shadowRadius: 4, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  heroGraphic: { width: 144, height: 144, borderRadius: 72, alignItems: "center", justifyContent: "center" },
  heroPulseHalo: { position: "absolute", width: 144, height: 144, borderRadius: 72, backgroundColor: "rgba(255, 218, 216, 0.4)" },
  heroImage: { width: 112, height: 112, borderRadius: 16 },
  message: { alignItems: "center", marginTop: 21 },
  title: { color: "#131b2e", fontSize: 25, lineHeight: 31, fontWeight: "800", letterSpacing: -0.8 },
  titleAccent: { color: "#c8102e" },
  description: { color: "#5c5b68", fontSize: 12, lineHeight: 17, textAlign: "center", maxWidth: 315, marginTop: 6 },
  actions: { gap: 9, marginTop: 21 },
  action: { height: 56, borderRadius: 16, paddingHorizontal: 20, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  primaryAction: { backgroundColor: "#d5082c", shadowColor: "#c8102e", shadowOpacity: 0.23, shadowRadius: 6, shadowOffset: { width: 0, height: 3 }, elevation: 3 },
  secondaryAction: { backgroundColor: "#ffffff", shadowColor: "#131b2e", shadowOpacity: 0.05, shadowRadius: 4, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  actionContent: { flexDirection: "row", alignItems: "center" },
  primaryIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.15)", alignItems: "center", justifyContent: "center", marginRight: 12 },
  donateIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: "#6cf8bb", alignItems: "center", justifyContent: "center", marginRight: 12 },
  primaryLabel: { color: "#ffffff", fontSize: 16, lineHeight: 20, fontWeight: "600" },
  primarySubtext: { color: "#ffdad8", fontSize: 11, lineHeight: 14, fontWeight: "700" },
  secondaryLabel: { color: "#131b2e", fontSize: 16, lineHeight: 20, fontWeight: "600" },
  secondarySubtext: { color: "#5c5b68", fontSize: 11, lineHeight: 14 },
  pressed: { opacity: 0.84, transform: [{ scale: 0.99 }] },
  footer: { alignItems: "center", marginTop: 18, gap: 8 },
  loginPrompt: { color: "#777480", fontSize: 11 },
  login: { color: "#9e001f", fontWeight: "700" },
  hospitalLink: { minHeight: 34, paddingHorizontal: 12, borderRadius: 8, backgroundColor: "#f2f3ff", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
  hospitalText: { color: "#5c5b68", fontSize: 11, lineHeight: 14, fontWeight: "700" },
});